<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <GenerateProgramFile>false</GenerateProgramFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="TestSupport.fs" />
        <Compile Include="DraftTests.fs" />
        <Compile Include="DispositionTests.fs" />
        <Compile Include="ProcessorTests.fs" />
        <Compile Include="MachineTests.fs" />
        <Compile Include="WorkSignalsTests.fs" />
        <Compile Include="Program.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Expecto" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" PrivateAssets="all" />
        <PackageReference Include="YoloDev.Expecto.TestSdk" PrivateAssets="all" />
        <PackageReference Include="coverlet.msbuild" PrivateAssets="all" />
        <ProjectReference Include="..\..\src\ByzantineSystems.Automata.Runtime\ByzantineSystems.Automata.Runtime.fsproj" />
    </ItemGroup>

</Project>
