<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="CoreTypeTests.fs" />
        <Compile Include="ChartTests.fs" />
        <Compile Include="ChartPropertyTests.fs" />
        <Compile Include="Program.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Expecto" />
        <PackageReference Include="FsCheck" />
        <ProjectReference Include="..\..\src\ByzantineSystems.Automata.Core\ByzantineSystems.Automata.Core.fsproj" />
    </ItemGroup>

</Project>
