<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <GenerateProgramFile>false</GenerateProgramFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="CoreTypeTests.fs" />
        <Compile Include="ChartTests.fs" />
        <Compile Include="ChartPropertyTests.fs" />
        <Compile Include="ChartFingerprintTests.fs" />
        <Compile Include="FragmentTests.fs" />
        <Compile Include="Program.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Expecto" />
        <PackageReference Include="FsCheck" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" PrivateAssets="all" />
        <PackageReference Include="YoloDev.Expecto.TestSdk" PrivateAssets="all" />
        <PackageReference Include="coverlet.msbuild" PrivateAssets="all" />
        <ProjectReference Include="..\..\src\ByzantineSystems.Automata.Core\ByzantineSystems.Automata.Core.fsproj" />
    </ItemGroup>

</Project>
