<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <GenerateProgramFile>false</GenerateProgramFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="TestContext.fs" />
        <Compile Include="SqlResourceTests.fs" />
        <Compile Include="CommandInboxTests.fs" />
        <Compile Include="ChartRegistryTests.fs" />
        <Compile Include="TemporalTests.fs" />
        <Compile Include="SchemaContractTests.fs" />
        <Compile Include="PostgresSupervisionStoreTests.fs" />
        <Compile Include="Program.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Expecto" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" PrivateAssets="all" />
        <PackageReference Include="YoloDev.Expecto.TestSdk" PrivateAssets="all" />
        <PackageReference Include="coverlet.msbuild" PrivateAssets="all" />
        <ProjectReference Include="..\..\src\ByzantineSystems.Automata.Storage.Postgres\ByzantineSystems.Automata.Storage.Postgres.fsproj" />
    </ItemGroup>

</Project>
