<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Serialization.fs" />
        <Compile Include="Sql.fs" />
        <Compile Include="PostgresStore.fs" />
        <Compile Include="Migrator.fs" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="migrations/main/*.sql" />
        <EmbeddedResource Include="migrations/repeatable/*.sql" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ByzantineSystems.Automata.Storage\ByzantineSystems.Automata.Storage.fsproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Npgsql" />
        <PackageReference Include="dbup-postgresql" />
        <PackageReference Include="FSharp.SystemTextJson" />
        <PackageReference Include="FsToolkit.ErrorHandling" />
    </ItemGroup>

</Project>
