// This code was generated by `SqlHydra.Npgsql` -- v5.0.0.
namespace ByzantineSystems.Automata.Storage.Postgres.Schema

open SqlHydra
open SqlHydra.Query

module Version =
    let cli = System.Version(5, 0, 0)
    let ns = "ByzantineSystems.Automata.Storage.Postgres.Schema"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns

module fsm =

    type belief =
        { [<ProviderDbType("Text")>]
          machine_id: Option<string>
          [<ProviderDbType("Text")>]
          entity_id: Option<string>
          [<ProviderDbType("Jsonb")>]
          state: Option<string>
          [<ProviderDbType("Text")>]
          status: Option<string>
          [<ProviderDbType("Bigint")>]
          epoch: Option<int64>
          [<ProviderDbType("Bigint")>]
          command_id: Option<int64>
          [<ProviderDbType("Integer")>]
          chart_version: Option<int>
          [<ProviderDbType("TimestampTz")>]
          valid_from: Option<System.DateTime>
          [<ProviderDbType("TimestampTz")>]
          valid_to: Option<System.DateTime>
          [<ProviderDbType("TimestampTz")>]
          known_from: Option<System.DateTime>
          [<ProviderDbType("TimestampTz")>]
          known_to: Option<System.DateTime> }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "machine_id"
                    Value = box this.machine_id
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "entity_id"
                    Value = box this.entity_id
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "state"
                    Value = box this.state
                    ProviderDbType = Some "Jsonb" }
                  { WriteColumn.Name = "status"
                    Value = box this.status
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "epoch"
                    Value = box this.epoch
                    ProviderDbType = Some "Bigint" }
                  { WriteColumn.Name = "command_id"
                    Value = box this.command_id
                    ProviderDbType = Some "Bigint" }
                  { WriteColumn.Name = "chart_version"
                    Value = box this.chart_version
                    ProviderDbType = Some "Integer" }
                  { WriteColumn.Name = "valid_from"
                    Value = box this.valid_from
                    ProviderDbType = Some "TimestampTz" }
                  { WriteColumn.Name = "valid_to"
                    Value = box this.valid_to
                    ProviderDbType = Some "TimestampTz" }
                  { WriteColumn.Name = "known_from"
                    Value = box this.known_from
                    ProviderDbType = Some "TimestampTz" }
                  { WriteColumn.Name = "known_to"
                    Value = box this.known_to
                    ProviderDbType = Some "TimestampTz" } ]

    let belief = table<belief>

    type belief_cold =
        { [<ProviderDbType("Text")>]
          machine_id: Option<string>
          [<ProviderDbType("Text")>]
          entity_id: Option<string>
          [<ProviderDbType("Jsonb")>]
          state: Option<string>
          [<ProviderDbType("Bigint")>]
          epoch: Option<int64>
          [<ProviderDbType("Bigint")>]
          command_id: Option<int64>
          [<ProviderDbType("Integer")>]
          chart_version: Option<int>
          [<ProviderDbType("TimestampTz")>]
          cutoff: Option<System.DateTime> }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "machine_id"
                    Value = box this.machine_id
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "entity_id"
                    Value = box this.entity_id
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "state"
                    Value = box this.state
                    ProviderDbType = Some "Jsonb" }
                  { WriteColumn.Name = "epoch"
                    Value = box this.epoch
                    ProviderDbType = Some "Bigint" }
                  { WriteColumn.Name = "command_id"
                    Value = box this.command_id
                    ProviderDbType = Some "Bigint" }
                  { WriteColumn.Name = "chart_version"
                    Value = box this.chart_version
                    ProviderDbType = Some "Integer" }
                  { WriteColumn.Name = "cutoff"
                    Value = box this.cutoff
                    ProviderDbType = Some "TimestampTz" } ]

    let belief_cold = table<belief_cold>

    type blocked_drift =
        { [<ProviderDbType("Bigint")>]
          command_id: Option<int64>
          [<ProviderDbType("Text")>]
          machine_id: Option<string>
          [<ProviderDbType("Text")>]
          entity_id: Option<string>
          [<ProviderDbType("Bigint")>]
          seq: Option<int64>
          [<ProviderDbType("Boolean")>]
          blocked: Option<bool>
          [<ProviderDbType("Boolean")>]
          expected_blocked: Option<bool> }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "command_id"
                    Value = box this.command_id
                    ProviderDbType = Some "Bigint" }
                  { WriteColumn.Name = "machine_id"
                    Value = box this.machine_id
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "entity_id"
                    Value = box this.entity_id
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "seq"
                    Value = box this.seq
                    ProviderDbType = Some "Bigint" }
                  { WriteColumn.Name = "blocked"
                    Value = box this.blocked
                    ProviderDbType = Some "Boolean" }
                  { WriteColumn.Name = "expected_blocked"
                    Value = box this.expected_blocked
                    ProviderDbType = Some "Boolean" } ]

    let blocked_drift = table<blocked_drift>

    type command =
        { [<ProviderDbType("Bigint")>]
          command_id: int64
          [<ProviderDbType("Text")>]
          machine_id: string
          [<ProviderDbType("Text")>]
          entity_id: string
          [<ProviderDbType("Bigint")>]
          seq: int64
          [<ProviderDbType("Text")>]
          idempotency_key: string
          [<ProviderDbType("Integer")>]
          chart_version: int
          [<ProviderDbType("Jsonb")>]
          event: string
          [<ProviderDbType("Text")>]
          kind: string
          [<ProviderDbType("Text")>]
          status: string
          [<ProviderDbType("Boolean")>]
          blocked: bool
          [<ProviderDbType("TimestampTz")>]
          visible_at: System.DateTime
          [<ProviderDbType("Bigint")>]
          lease_token: int64
          [<ProviderDbType("Integer")>]
          read_ct: int
          [<ProviderDbType("Integer")>]
          attempts: int
          [<ProviderDbType("TimestampTz")>]
          received_at: System.DateTime
          [<ProviderDbType("Text")>]
          tenant: string
          [<ProviderDbType("Text")>]
          principal: string
          [<ProviderDbType("Text")>]
          source: string
          [<ProviderDbType("Text")>]
          correlation_id: string
          [<ProviderDbType("Text")>]
          causation_id: string }

        interface IHasWrite<command_write> with
            /// This row's writable columns, as `writeEntity` takes them: `toWrite row`.
            member this.ToWrite() : command_write =
                { machine_id = this.machine_id
                  entity_id = this.entity_id
                  seq = this.seq
                  idempotency_key = this.idempotency_key
                  chart_version = this.chart_version
                  event = this.event
                  kind = this.kind
                  status = this.status
                  blocked = this.blocked
                  visible_at = this.visible_at
                  lease_token = this.lease_token
                  read_ct = this.read_ct
                  attempts = this.attempts
                  received_at = this.received_at
                  tenant = this.tenant
                  principal = this.principal
                  source = this.source
                  correlation_id = this.correlation_id
                  causation_id = this.causation_id }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "machine_id"
                    Value = box this.machine_id
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "entity_id"
                    Value = box this.entity_id
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "seq"
                    Value = box this.seq
                    ProviderDbType = Some "Bigint" }
                  { WriteColumn.Name = "idempotency_key"
                    Value = box this.idempotency_key
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "chart_version"
                    Value = box this.chart_version
                    ProviderDbType = Some "Integer" }
                  { WriteColumn.Name = "event"
                    Value = box this.event
                    ProviderDbType = Some "Jsonb" }
                  { WriteColumn.Name = "kind"
                    Value = box this.kind
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "status"
                    Value = box this.status
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "blocked"
                    Value = box this.blocked
                    ProviderDbType = Some "Boolean" }
                  { WriteColumn.Name = "visible_at"
                    Value = box this.visible_at
                    ProviderDbType = Some "TimestampTz" }
                  { WriteColumn.Name = "lease_token"
                    Value = box this.lease_token
                    ProviderDbType = Some "Bigint" }
                  { WriteColumn.Name = "read_ct"
                    Value = box this.read_ct
                    ProviderDbType = Some "Integer" }
                  { WriteColumn.Name = "attempts"
                    Value = box this.attempts
                    ProviderDbType = Some "Integer" }
                  { WriteColumn.Name = "received_at"
                    Value = box this.received_at
                    ProviderDbType = Some "TimestampTz" }
                  { WriteColumn.Name = "tenant"
                    Value = box this.tenant
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "principal"
                    Value = box this.principal
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "source"
                    Value = box this.source
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "correlation_id"
                    Value = box this.correlation_id
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "causation_id"
                    Value = box this.causation_id
                    ProviderDbType = Some "Text" } ]

    /// The columns of `command` a caller may write; the database owns the rest.
    and command_write =
        { [<ProviderDbType("Text")>]
          machine_id: string
          [<ProviderDbType("Text")>]
          entity_id: string
          [<ProviderDbType("Bigint")>]
          seq: int64
          [<ProviderDbType("Text")>]
          idempotency_key: string
          [<ProviderDbType("Integer")>]
          chart_version: int
          [<ProviderDbType("Jsonb")>]
          event: string
          [<ProviderDbType("Text")>]
          kind: string
          [<ProviderDbType("Text")>]
          status: string
          [<ProviderDbType("Boolean")>]
          blocked: bool
          [<ProviderDbType("TimestampTz")>]
          visible_at: System.DateTime
          [<ProviderDbType("Bigint")>]
          lease_token: int64
          [<ProviderDbType("Integer")>]
          read_ct: int
          [<ProviderDbType("Integer")>]
          attempts: int
          [<ProviderDbType("TimestampTz")>]
          received_at: System.DateTime
          [<ProviderDbType("Text")>]
          tenant: string
          [<ProviderDbType("Text")>]
          principal: string
          [<ProviderDbType("Text")>]
          source: string
          [<ProviderDbType("Text")>]
          correlation_id: string
          [<ProviderDbType("Text")>]
          causation_id: string }

        interface IWriteOf<command> with
            member this.WriteColumns =
                [ { WriteColumn.Name = "machine_id"
                    Value = box this.machine_id
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "entity_id"
                    Value = box this.entity_id
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "seq"
                    Value = box this.seq
                    ProviderDbType = Some "Bigint" }
                  { WriteColumn.Name = "idempotency_key"
                    Value = box this.idempotency_key
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "chart_version"
                    Value = box this.chart_version
                    ProviderDbType = Some "Integer" }
                  { WriteColumn.Name = "event"
                    Value = box this.event
                    ProviderDbType = Some "Jsonb" }
                  { WriteColumn.Name = "kind"
                    Value = box this.kind
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "status"
                    Value = box this.status
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "blocked"
                    Value = box this.blocked
                    ProviderDbType = Some "Boolean" }
                  { WriteColumn.Name = "visible_at"
                    Value = box this.visible_at
                    ProviderDbType = Some "TimestampTz" }
                  { WriteColumn.Name = "lease_token"
                    Value = box this.lease_token
                    ProviderDbType = Some "Bigint" }
                  { WriteColumn.Name = "read_ct"
                    Value = box this.read_ct
                    ProviderDbType = Some "Integer" }
                  { WriteColumn.Name = "attempts"
                    Value = box this.attempts
                    ProviderDbType = Some "Integer" }
                  { WriteColumn.Name = "received_at"
                    Value = box this.received_at
                    ProviderDbType = Some "TimestampTz" }
                  { WriteColumn.Name = "tenant"
                    Value = box this.tenant
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "principal"
                    Value = box this.principal
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "source"
                    Value = box this.source
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "correlation_id"
                    Value = box this.correlation_id
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "causation_id"
                    Value = box this.causation_id
                    ProviderDbType = Some "Text" } ]

    let command = table<command>

    type command_correction =
        { [<ProviderDbType("Bigint")>]
          command_id: int64
          [<ProviderDbType("TimestampTz")>]
          effective_at: System.DateTime
          [<ProviderDbType("Text")>]
          on_divergence: string
          [<ProviderDbType("Integer")>]
          replay_limit: int }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "command_id"
                    Value = box this.command_id
                    ProviderDbType = Some "Bigint" }
                  { WriteColumn.Name = "effective_at"
                    Value = box this.effective_at
                    ProviderDbType = Some "TimestampTz" }
                  { WriteColumn.Name = "on_divergence"
                    Value = box this.on_divergence
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "replay_limit"
                    Value = box this.replay_limit
                    ProviderDbType = Some "Integer" } ]

    let command_correction = table<command_correction>

    type command_error =
        { [<ProviderDbType("Bigint")>]
          command_id: int64
          [<ProviderDbType("Jsonb")>]
          error: string
          [<ProviderDbType("TimestampTz")>]
          recorded_at: System.DateTime }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "command_id"
                    Value = box this.command_id
                    ProviderDbType = Some "Bigint" }
                  { WriteColumn.Name = "error"
                    Value = box this.error
                    ProviderDbType = Some "Jsonb" }
                  { WriteColumn.Name = "recorded_at"
                    Value = box this.recorded_at
                    ProviderDbType = Some "TimestampTz" } ]

    let command_error = table<command_error>

    type current_belief =
        { [<ProviderDbType("Text")>]
          machine_id: Option<string>
          [<ProviderDbType("Text")>]
          entity_id: Option<string>
          [<ProviderDbType("Jsonb")>]
          state: Option<string>
          [<ProviderDbType("Text")>]
          status: Option<string>
          [<ProviderDbType("Bigint")>]
          epoch: Option<int64>
          [<ProviderDbType("Bigint")>]
          command_id: Option<int64>
          [<ProviderDbType("Integer")>]
          chart_version: Option<int>
          [<ProviderDbType("TimestampTz")>]
          valid_from: Option<System.DateTime>
          [<ProviderDbType("TimestampTz")>]
          known_from: Option<System.DateTime> }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "machine_id"
                    Value = box this.machine_id
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "entity_id"
                    Value = box this.entity_id
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "state"
                    Value = box this.state
                    ProviderDbType = Some "Jsonb" }
                  { WriteColumn.Name = "status"
                    Value = box this.status
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "epoch"
                    Value = box this.epoch
                    ProviderDbType = Some "Bigint" }
                  { WriteColumn.Name = "command_id"
                    Value = box this.command_id
                    ProviderDbType = Some "Bigint" }
                  { WriteColumn.Name = "chart_version"
                    Value = box this.chart_version
                    ProviderDbType = Some "Integer" }
                  { WriteColumn.Name = "valid_from"
                    Value = box this.valid_from
                    ProviderDbType = Some "TimestampTz" }
                  { WriteColumn.Name = "known_from"
                    Value = box this.known_from
                    ProviderDbType = Some "TimestampTz" } ]

    let current_belief = table<current_belief>

    type supervision_event =
        { [<ProviderDbType("Bigint")>]
          id: int64
          [<ProviderDbType("Text")>]
          supervisor: string
          [<ProviderDbType("Text")>]
          child_id: string
          [<ProviderDbType("Text")>]
          kind: string
          [<ProviderDbType("Text")>]
          strategy: string
          [<ProviderDbType("Jsonb")>]
          reason: string
          [<ProviderDbType("TimestampTz")>]
          at: System.DateTime }

        interface IHasWrite<supervision_event_write> with
            /// This row's writable columns, as `writeEntity` takes them: `toWrite row`.
            member this.ToWrite() : supervision_event_write =
                { supervisor = this.supervisor
                  child_id = this.child_id
                  kind = this.kind
                  strategy = this.strategy
                  reason = this.reason
                  at = this.at }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "supervisor"
                    Value = box this.supervisor
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "child_id"
                    Value = box this.child_id
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "kind"
                    Value = box this.kind
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "strategy"
                    Value = box this.strategy
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "reason"
                    Value = box this.reason
                    ProviderDbType = Some "Jsonb" }
                  { WriteColumn.Name = "at"
                    Value = box this.at
                    ProviderDbType = Some "TimestampTz" } ]

    /// The columns of `supervision_event` a caller may write; the database owns the rest.
    and supervision_event_write =
        { [<ProviderDbType("Text")>]
          supervisor: string
          [<ProviderDbType("Text")>]
          child_id: string
          [<ProviderDbType("Text")>]
          kind: string
          [<ProviderDbType("Text")>]
          strategy: string
          [<ProviderDbType("Jsonb")>]
          reason: string
          [<ProviderDbType("TimestampTz")>]
          at: System.DateTime }

        interface IWriteOf<supervision_event> with
            member this.WriteColumns =
                [ { WriteColumn.Name = "supervisor"
                    Value = box this.supervisor
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "child_id"
                    Value = box this.child_id
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "kind"
                    Value = box this.kind
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "strategy"
                    Value = box this.strategy
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "reason"
                    Value = box this.reason
                    ProviderDbType = Some "Jsonb" }
                  { WriteColumn.Name = "at"
                    Value = box this.at
                    ProviderDbType = Some "TimestampTz" } ]

    let supervision_event = table<supervision_event>

    type transition =
        { [<ProviderDbType("Text")>]
          machine_id: string
          [<ProviderDbType("Text")>]
          entity_id: string
          [<ProviderDbType("Bigint")>]
          epoch: int64
          [<ProviderDbType("Bigint")>]
          command_id: int64
          [<ProviderDbType("Integer")>]
          chart_version: int
          [<ProviderDbType("Jsonb")>]
          event: string
          [<ProviderDbType("Jsonb")>]
          actions: string
          [<ProviderDbType("Jsonb")>]
          from_state: string
          [<ProviderDbType("Jsonb")>]
          to_state: string
          [<ProviderDbType("Text")>]
          handled_by: string
          [<ProviderDbType("Text,Array")>]
          exited: string[]
          [<ProviderDbType("Text,Array")>]
          entered: string[]
          [<ProviderDbType("Text")>]
          status: string
          [<ProviderDbType("TimestampTz")>]
          effective_at: System.DateTime
          [<ProviderDbType("TimestampTz")>]
          committed_at: System.DateTime }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "machine_id"
                    Value = box this.machine_id
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "entity_id"
                    Value = box this.entity_id
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "epoch"
                    Value = box this.epoch
                    ProviderDbType = Some "Bigint" }
                  { WriteColumn.Name = "command_id"
                    Value = box this.command_id
                    ProviderDbType = Some "Bigint" }
                  { WriteColumn.Name = "chart_version"
                    Value = box this.chart_version
                    ProviderDbType = Some "Integer" }
                  { WriteColumn.Name = "event"
                    Value = box this.event
                    ProviderDbType = Some "Jsonb" }
                  { WriteColumn.Name = "actions"
                    Value = box this.actions
                    ProviderDbType = Some "Jsonb" }
                  { WriteColumn.Name = "from_state"
                    Value = box this.from_state
                    ProviderDbType = Some "Jsonb" }
                  { WriteColumn.Name = "to_state"
                    Value = box this.to_state
                    ProviderDbType = Some "Jsonb" }
                  { WriteColumn.Name = "handled_by"
                    Value = box this.handled_by
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "exited"
                    Value = box this.exited
                    ProviderDbType = Some "Text,Array" }
                  { WriteColumn.Name = "entered"
                    Value = box this.entered
                    ProviderDbType = Some "Text,Array" }
                  { WriteColumn.Name = "status"
                    Value = box this.status
                    ProviderDbType = Some "Text" }
                  { WriteColumn.Name = "effective_at"
                    Value = box this.effective_at
                    ProviderDbType = Some "TimestampTz" }
                  { WriteColumn.Name = "committed_at"
                    Value = box this.committed_at
                    ProviderDbType = Some "TimestampTz" } ]

    let transition = table<transition>



type QueryContextFactory =
    {
        OpenContext: unit -> QueryContext
        OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext>
        /// Disposes the NpgsqlDataSource when the factory created it from a connection string; a no-op when the caller supplied their own.
        Dispose: unit -> unit
    }

    interface System.IDisposable with
        member this.Dispose() = this.Dispose()

    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()

    static member Create(connectionString: string, ?sqlLogger) =
        // The factory creates this data source, so it owns and disposes it.
        let dataSource = Npgsql.NpgsqlDataSource.Create(connectionString)
        QueryContextFactory.CreateInternal(dataSource, (fun () -> dataSource.Dispose()), ?sqlLogger = sqlLogger)

    static member Create(dataSource: Npgsql.NpgsqlDataSource, ?sqlLogger) =
        // The caller supplied this data source, so the caller owns its lifetime.
        QueryContextFactory.CreateInternal(dataSource, ignore, ?sqlLogger = sqlLogger)

    static member private CreateInternal(dataSource: Npgsql.NpgsqlDataSource, dispose: unit -> unit, ?sqlLogger) =
        let emitter = SqlHydra.Query.PostgresEmitter()

        let createConn () : System.Data.Common.DbConnection = dataSource.OpenConnection()

        let openContext () =
            let conn = createConn ()
            let ctx = new QueryContext(conn, emitter)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {
                let! conn = dataSource.OpenConnectionAsync()
                let ctx = new QueryContext(conn, emitter)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }

        { OpenContext = openContext
          OpenContextAsync = openContextAsync
          Dispose = dispose }
