// This code was generated by `SqlHydra.Sqlite` -- v5.0.0.
namespace ByzantineSystems.Automata.Storage.Sqlite.Schema

open SqlHydra
open SqlHydra.Query

module Version =
    let cli = System.Version(5, 0, 0)
    let ns = "ByzantineSystems.Automata.Storage.Sqlite.Schema"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns

module main =

    type fsm_action =
        { command_id: int64
          ordinal: int64
          machine_id: string
          entity_id: string
          epoch: int64
          action: string
          visible_at: int64
          lease_token: int64
          read_ct: int64
          enqueued_at: int64 }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "command_id"
                    Value = box this.command_id
                    ProviderDbType = None }
                  { WriteColumn.Name = "ordinal"
                    Value = box this.ordinal
                    ProviderDbType = None }
                  { WriteColumn.Name = "machine_id"
                    Value = box this.machine_id
                    ProviderDbType = None }
                  { WriteColumn.Name = "entity_id"
                    Value = box this.entity_id
                    ProviderDbType = None }
                  { WriteColumn.Name = "epoch"
                    Value = box this.epoch
                    ProviderDbType = None }
                  { WriteColumn.Name = "action"
                    Value = box this.action
                    ProviderDbType = None }
                  { WriteColumn.Name = "visible_at"
                    Value = box this.visible_at
                    ProviderDbType = None }
                  { WriteColumn.Name = "lease_token"
                    Value = box this.lease_token
                    ProviderDbType = None }
                  { WriteColumn.Name = "read_ct"
                    Value = box this.read_ct
                    ProviderDbType = None }
                  { WriteColumn.Name = "enqueued_at"
                    Value = box this.enqueued_at
                    ProviderDbType = None } ]

    let fsm_action = table<fsm_action>

    type fsm_action_dead_letter =
        { machine_id: string
          entity_id: string
          command_id: int64
          epoch: int64
          ordinal: int64
          action: string
          reason: string
          deliveries: int64
          recorded_at: int64 }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "machine_id"
                    Value = box this.machine_id
                    ProviderDbType = None }
                  { WriteColumn.Name = "entity_id"
                    Value = box this.entity_id
                    ProviderDbType = None }
                  { WriteColumn.Name = "command_id"
                    Value = box this.command_id
                    ProviderDbType = None }
                  { WriteColumn.Name = "epoch"
                    Value = box this.epoch
                    ProviderDbType = None }
                  { WriteColumn.Name = "ordinal"
                    Value = box this.ordinal
                    ProviderDbType = None }
                  { WriteColumn.Name = "action"
                    Value = box this.action
                    ProviderDbType = None }
                  { WriteColumn.Name = "reason"
                    Value = box this.reason
                    ProviderDbType = None }
                  { WriteColumn.Name = "deliveries"
                    Value = box this.deliveries
                    ProviderDbType = None }
                  { WriteColumn.Name = "recorded_at"
                    Value = box this.recorded_at
                    ProviderDbType = None } ]

    let fsm_action_dead_letter = table<fsm_action_dead_letter>

    type fsm_command =
        { command_id: int64
          machine_id: string
          entity_id: string
          seq: int64
          idempotency_key: string
          chart_version: int64
          event: string
          kind: string
          status: string
          blocked: int64
          visible_at: int64
          lease_token: int64
          read_ct: int64
          attempts: int64
          received_at: int64
          tenant: string
          principal: string
          source: string
          correlation_id: string
          causation_id: string }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "command_id"
                    Value = box this.command_id
                    ProviderDbType = None }
                  { WriteColumn.Name = "machine_id"
                    Value = box this.machine_id
                    ProviderDbType = None }
                  { WriteColumn.Name = "entity_id"
                    Value = box this.entity_id
                    ProviderDbType = None }
                  { WriteColumn.Name = "seq"
                    Value = box this.seq
                    ProviderDbType = None }
                  { WriteColumn.Name = "idempotency_key"
                    Value = box this.idempotency_key
                    ProviderDbType = None }
                  { WriteColumn.Name = "chart_version"
                    Value = box this.chart_version
                    ProviderDbType = None }
                  { WriteColumn.Name = "event"
                    Value = box this.event
                    ProviderDbType = None }
                  { WriteColumn.Name = "kind"
                    Value = box this.kind
                    ProviderDbType = None }
                  { WriteColumn.Name = "status"
                    Value = box this.status
                    ProviderDbType = None }
                  { WriteColumn.Name = "blocked"
                    Value = box this.blocked
                    ProviderDbType = None }
                  { WriteColumn.Name = "visible_at"
                    Value = box this.visible_at
                    ProviderDbType = None }
                  { WriteColumn.Name = "lease_token"
                    Value = box this.lease_token
                    ProviderDbType = None }
                  { WriteColumn.Name = "read_ct"
                    Value = box this.read_ct
                    ProviderDbType = None }
                  { WriteColumn.Name = "attempts"
                    Value = box this.attempts
                    ProviderDbType = None }
                  { WriteColumn.Name = "received_at"
                    Value = box this.received_at
                    ProviderDbType = None }
                  { WriteColumn.Name = "tenant"
                    Value = box this.tenant
                    ProviderDbType = None }
                  { WriteColumn.Name = "principal"
                    Value = box this.principal
                    ProviderDbType = None }
                  { WriteColumn.Name = "source"
                    Value = box this.source
                    ProviderDbType = None }
                  { WriteColumn.Name = "correlation_id"
                    Value = box this.correlation_id
                    ProviderDbType = None }
                  { WriteColumn.Name = "causation_id"
                    Value = box this.causation_id
                    ProviderDbType = None } ]

    let fsm_command = table<fsm_command>

    type fsm_command_correction =
        { command_id: int64
          effective_at: int64
          on_divergence: string
          replay_limit: int64 }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "command_id"
                    Value = box this.command_id
                    ProviderDbType = None }
                  { WriteColumn.Name = "effective_at"
                    Value = box this.effective_at
                    ProviderDbType = None }
                  { WriteColumn.Name = "on_divergence"
                    Value = box this.on_divergence
                    ProviderDbType = None }
                  { WriteColumn.Name = "replay_limit"
                    Value = box this.replay_limit
                    ProviderDbType = None } ]

    let fsm_command_correction = table<fsm_command_correction>

    type fsm_command_error =
        { command_id: int64
          error: string
          recorded_at: int64 }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "command_id"
                    Value = box this.command_id
                    ProviderDbType = None }
                  { WriteColumn.Name = "error"
                    Value = box this.error
                    ProviderDbType = None }
                  { WriteColumn.Name = "recorded_at"
                    Value = box this.recorded_at
                    ProviderDbType = None } ]

    let fsm_command_error = table<fsm_command_error>

    type fsm_entity_snapshot =
        { machine_id: string
          entity_id: string
          state: string
          status: string
          epoch: int64
          command_id: int64
          chart_version: int64
          effective_at: int64
          committed_at: int64 }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "machine_id"
                    Value = box this.machine_id
                    ProviderDbType = None }
                  { WriteColumn.Name = "entity_id"
                    Value = box this.entity_id
                    ProviderDbType = None }
                  { WriteColumn.Name = "state"
                    Value = box this.state
                    ProviderDbType = None }
                  { WriteColumn.Name = "status"
                    Value = box this.status
                    ProviderDbType = None }
                  { WriteColumn.Name = "epoch"
                    Value = box this.epoch
                    ProviderDbType = None }
                  { WriteColumn.Name = "command_id"
                    Value = box this.command_id
                    ProviderDbType = None }
                  { WriteColumn.Name = "chart_version"
                    Value = box this.chart_version
                    ProviderDbType = None }
                  { WriteColumn.Name = "effective_at"
                    Value = box this.effective_at
                    ProviderDbType = None }
                  { WriteColumn.Name = "committed_at"
                    Value = box this.committed_at
                    ProviderDbType = None } ]

    let fsm_entity_snapshot = table<fsm_entity_snapshot>

    type fsm_machine_chart_version =
        { machine_id: string
          version: int64
          fingerprint: string
          registered_at: int64 }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "machine_id"
                    Value = box this.machine_id
                    ProviderDbType = None }
                  { WriteColumn.Name = "version"
                    Value = box this.version
                    ProviderDbType = None }
                  { WriteColumn.Name = "fingerprint"
                    Value = box this.fingerprint
                    ProviderDbType = None }
                  { WriteColumn.Name = "registered_at"
                    Value = box this.registered_at
                    ProviderDbType = None } ]

    let fsm_machine_chart_version = table<fsm_machine_chart_version>

    type fsm_transition =
        { machine_id: string
          entity_id: string
          epoch: int64
          command_id: int64
          chart_version: int64
          event: string
          actions: string
          from_state: string
          to_state: string
          handled_by: string
          exited: string
          entered: string
          status: string
          effective_at: int64
          committed_at: int64 }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "machine_id"
                    Value = box this.machine_id
                    ProviderDbType = None }
                  { WriteColumn.Name = "entity_id"
                    Value = box this.entity_id
                    ProviderDbType = None }
                  { WriteColumn.Name = "epoch"
                    Value = box this.epoch
                    ProviderDbType = None }
                  { WriteColumn.Name = "command_id"
                    Value = box this.command_id
                    ProviderDbType = None }
                  { WriteColumn.Name = "chart_version"
                    Value = box this.chart_version
                    ProviderDbType = None }
                  { WriteColumn.Name = "event"
                    Value = box this.event
                    ProviderDbType = None }
                  { WriteColumn.Name = "actions"
                    Value = box this.actions
                    ProviderDbType = None }
                  { WriteColumn.Name = "from_state"
                    Value = box this.from_state
                    ProviderDbType = None }
                  { WriteColumn.Name = "to_state"
                    Value = box this.to_state
                    ProviderDbType = None }
                  { WriteColumn.Name = "handled_by"
                    Value = box this.handled_by
                    ProviderDbType = None }
                  { WriteColumn.Name = "exited"
                    Value = box this.exited
                    ProviderDbType = None }
                  { WriteColumn.Name = "entered"
                    Value = box this.entered
                    ProviderDbType = None }
                  { WriteColumn.Name = "status"
                    Value = box this.status
                    ProviderDbType = None }
                  { WriteColumn.Name = "effective_at"
                    Value = box this.effective_at
                    ProviderDbType = None }
                  { WriteColumn.Name = "committed_at"
                    Value = box this.committed_at
                    ProviderDbType = None } ]

    let fsm_transition = table<fsm_transition>



type QueryContextFactory =
    { OpenContext: unit -> QueryContext
      OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext> }
    // This provider holds no factory-level resources; each connection is owned and disposed by its QueryContext.
    member _.Dispose() = ()

    interface System.IDisposable with
        member this.Dispose() = this.Dispose()

    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()

    static member Create(connectionString: string, ?sqlLogger) =
        let emitter = SqlHydra.Query.SqliteEmitter()

        let createConn () : System.Data.Common.DbConnection =
            new Microsoft.Data.Sqlite.SqliteConnection(connectionString)

        let openContext () =
            let conn = createConn ()
            conn.Open()
            let ctx = new QueryContext(conn, emitter)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {
                let conn = createConn ()
                do! conn.OpenAsync()
                let ctx = new QueryContext(conn, emitter)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }

        { OpenContext = openContext
          OpenContextAsync = openContextAsync }
