<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Envelope.fs" />
        <Compile Include="Store.fs" />
        <Compile Include="Command.fs" />
        <Compile Include="ChartRegistry.fs" />
        <Compile Include="Supervision.fs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ByzantineSystems.Automata.Core\ByzantineSystems.Automata.Core.fsproj" />
    </ItemGroup>

</Project>
