<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <GenerateProgramFile>false</GenerateProgramFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="ResiliencePipelineTests.fs" />
        <Compile Include="SupervisorTests.fs" />
        <Compile Include="Program.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Expecto" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" PrivateAssets="all" />
        <PackageReference Include="YoloDev.Expecto.TestSdk" PrivateAssets="all" />
        <PackageReference Include="coverlet.msbuild" PrivateAssets="all" />
        <ProjectReference Include="..\..\src\ByzantineSystems.Automata.Resilience\ByzantineSystems.Automata.Resilience.fsproj" />
    </ItemGroup>

</Project>
