<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Telemetry.fs" />
        <Compile Include="TransientPolicy.fs" />
        <Compile Include="Supervisor.fs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ByzantineSystems.Automata.Core\ByzantineSystems.Automata.Core.fsproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Polly.Core" />
    </ItemGroup>

</Project>
