<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Placeholder.fs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ByzantineSystems.Automata.Storage\ByzantineSystems.Automata.Storage.fsproj" />
    </ItemGroup>

</Project>
