<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Identifiers.fs" />
        <Compile Include="Transition.fs" />
        <Compile Include="Errors.fs" />
        <Compile Include="Codec.fs" />
    </ItemGroup>

</Project>
